service: test-xray

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: testbucket

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: "/"
          method: "get"
          integration: "lambda-proxy"

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

custom: ${file(./config.yml):custom}
